name: Python package

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest --junitxml=results.xml

    - name: Publish Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: results.xml

  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: tomershukhman/capitolis:${{ github.sha }}

    - name: Logout from Docker Hub
      run: docker logout

  update_k8s_deployment:
    runs-on: ubuntu-latest
    needs: build_and_push_docker

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update Kubernetes deployment
      run: |
        sed -i 's|image: tomershukhman/capitolis:.*|image: tomershukhman/capitolis:${{ github.sha }}|' deployment.yaml
        cat deployment.yaml